language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          env: TOXENV=py32
        - os: linux
          sudo: required
          python: 3.5
          env: TOXENV=py33
        - os: osx
          language: generic
          env: TOXENV=py32
        - os: osx
          language: generic
          env: TOXENV=py33
cache:
  - pip
  - apt
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy matplotlib
  - source activate test-environment
  - "pip install flake8 pylint"
  - "pip install -r requirements.txt"
script:
  - flake8 
  - pylint image_registration.py
