sudo: true
language: python
python:
  - "2.7"
cache:
 apt
 directories:
  - $HOME/.cache/pip
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
install: 
  - "pip install flake8 pylint"
  - "pip install -r requirements.txt"
script:
  - flake8 
  - pylint image_registration.py 